name: CI

on:
  push:
    branches: [ main, master ]
    paths:
      - "src/**"
      - "dashboard/**"
      - "data/**"
      - "models/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
      # Rutas usadas por tus scripts
      DATA_PATH: data/processed/train.parquet
      RESULTS_DIR: results/dashboard

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Herramientas de CI opcionales (no tocan tu requirements.txt)
          pip install pytest ruff

      # (Opcional) Traer datos con DVC si definís secretos/remote
      - name: DVC pull (optional)
        if: ${{ secrets.DVC_REMOTE_URL != '' }}
        run: |
          pip install "dvc[all]"
          dvc remote add -f origin "${{ secrets.DVC_REMOTE_URL }}"
          # Si tu remote requiere credenciales, configúralas en secretos
          # dvc remote modify origin --local access_key_id  "${{ secrets.DVC_ACCESS_KEY }}"
          # dvc remote modify origin --local secret_access_key "${{ secrets.DVC_SECRET_KEY }}"
          dvc pull || echo "DVC pull skipped or failed (no remote?)"

      - name: Lint (ruff)
        run: |
          ruff --version
          # No fallar si hay warnings; cambia a --format=github y quita || true para hacer obligatorio
          ruff check . || true

      - name: Smoke checks (syntax & imports)
        run: |
          # Compilar a bytecode (atrapa errores de sintaxis)
          python -m py_compile $(git ls-files '*.py')
          # Chequeos rápidos sin lanzar el servidor de Streamlit
          python - << 'PY'
          from pathlib import Path
          import pandas as pd
          p = Path("data/processed/train.parquet")
          if p.exists():
              df = pd.read_parquet(p)
              print("Data OK:", df.shape, "index tz:", getattr(df.index, "tz", None))
          else:
              print("WARN: dataset no encontrado:", p)
          print("Imports OK")
          PY

      - name: Run tests (if present)
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests/ directory. Skipping."
          fi

      - name: Produce dashboard snapshot (optional smoke)
        run: |
          # Intento mínimo de ejecutar funciones sin levantar el server:
          # Si tu app depende de modelos pesados, este paso se salta si no existen.
          python - << 'PY'
          from pathlib import Path
          import pandas as pd
          models_ok = Path("models").exists()
          data_ok = Path("data/processed/train.parquet").exists()
          if models_ok and data_ok:
              # Generar un CSV vacío para comprobar artefactos
              out = Path("results/dashboard/last_snapshot.csv")
              out.parent.mkdir(parents=True, exist_ok=True)
              pd.DataFrame({"ok": [1]}).to_csv(out, index=False)
              print("Snapshot dummy creado:", out)
          else:
              print("Saltando snapshot (faltan modelos o datos)")
          PY

      - name: Upload snapshot artifact (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-snapshot
          path: results/dashboard/last_snapshot.csv
          if-no-files-found: ignore
