name: Docker Image

on:
  push:
    tags: [ "v*" ]        # corre al publicar tags tipo v1.0.0
  workflow_dispatch:      # corre manualmente desde Actions

permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ── Gate: si no hay Dockerfile, marcamos skip=true y no hacemos nada ──
      - name: Check for Dockerfile
        id: gate
        run: |
          if [ -f Dockerfile ]; then
            echo "skip=false" >> "$GITHUB_OUTPUT"
          else
            echo "No Dockerfile found, skipping build."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Buildx
        if: ${{ steps.gate.outputs.skip !=
